# simple czalculator
print("This is a simple calculator code")
a=20
b=5
print("addition =",a+b)
print("subtraction=",a-b)
print("multiplication=",a*b)
print("division=",a / b)
print("floor division=",a // b)
print("remainder=", a % b)
print("power=", a**b)
print('####################################################################################')
# addition
a=20
b=30
print("the add value is:",50)
print(a+b)
print('######################################################################')
# subtract
a=30
b=10
print(a-b)
print('###################################################################')
# multiplication
a=30
b=10
print(a*b)
print('#########################################################################')
# division
#floor division
#modulus
#power
#mixed arithmetic
a=20
b=5
c=10
print(a*b+c)
print('############################################################################')
#averge of numbers
a=10
b=20
c=30
avg=(a+b+c/3)
print(avg)
print('#####################################################################')
# 
a=2
b=3
c=4
print((a +b ) * c)
print('##############################################################################')
#
a=10
b=20
c=5
print((a-b) * c)
print('#########################################################################')
# add then divide
a=5
b=10
c=10
print((a+b)/c)
print('####################################################################')
